# Generated by Django 5.2 on 2025-04-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
