# Generated by Django 5.2 on 2025-04-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_email_verification_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_code_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
