# Generated by Django 5.2 on 2025-04-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_email_code_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="admin_chatBot_key",
        ),
    ]
