# Generated by Django 5.2 on 2025-04-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_customuser_admin_chatbot_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="api_key",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
