# Generated by Django 5.2 on 2025-04-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="chatBot_user_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
