# Generated by Django 5.2 on 2025-04-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_customuser_chatbot_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="lofty_access_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="lofty_refresh_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="lofty_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="lofty_user_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
