# Generated by Django 5.2 on 2025-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="chatbot_create_account_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="chatbot_create_user_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
