# Generated by Django 5.2 on 2025-05-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_systemsettings_chatbot_create_account_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotIntegrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                (
                    "chatbot_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("action", models.CharField(max_length=50)),
                ("status_code", models.IntegerField()),
                ("success", models.BooleanField(default=False)),
                ("response_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
