# Generated by Django 5.2 on 2025-05-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0004_systemsettings_stripe_publishable_key_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemsettings",
            old_name="stripe_publishable_key",
            new_name="stripe_api_key",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="stripe_secret_key",
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="stripe_billing_portal_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="stripe_product_monthly_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="stripe_product_yearly_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
