# Generated by Django 5.2 on 2025-05-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "system",
            "0005_rename_stripe_publishable_key_systemsettings_stripe_api_key_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="stripe_product_monthly_id",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="stripe_product_yearly_id",
        ),
    ]
