# Generated by Django 5.2 on 2025-05-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0006_remove_systemsettings_stripe_product_monthly_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemsettings",
            old_name="stripe_billing_portal_url",
            new_name="stripe_return_url",
        ),
    ]
