# Generated by Django 5.2 on 2025-05-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "system",
            "0007_rename_stripe_billing_portal_url_systemsettings_stripe_return_url",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="instabot_ai_prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
