# Generated by Django 5.2 on 2025-06-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0008_systemsettings_instabot_ai_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="base_url",
            field=models.URLField(
                blank=True,
                help_text="Base URL of your frontend or domain used in links.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_footer_text",
            field=models.TextField(
                blank=True,
                help_text="Text shown at the bottom of system emails.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_from",
            field=models.EmailField(
                blank=True,
                help_text="Default from email address used in system emails.",
                max_length=254,
                null=True,
            ),
        ),
    ]
