# Generated by Django 5.2 on 2025-06-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0009_systemsettings_base_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemsettings",
            old_name="base_url",
            new_name="frontend_base_url",
        ),
    ]
