# Generated by Django 5.2 on 2025-06-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0010_rename_base_url_systemsettings_frontend_base_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="email_support",
            field=models.EmailField(
                blank=True,
                help_text="Support email address for users to contact.",
                max_length=254,
                null=True,
            ),
        ),
    ]
