# Generated by Django 5.2 on 2025-07-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0011_systemsettings_email_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="stripe_api_version",
            field=models.TextField(blank=True, default="2024-04-10", null=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="stripe_secret_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
