# Generated by Django 5.2 on 2025-07-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0012_systemsettings_stripe_api_version_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="stripe_api_version",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="stripe_secret_key",
        ),
    ]
