# Generated by Django 5.2 on 2025-07-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0013_remove_systemsettings_stripe_api_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="openAI_api_key",
            field=models.TextField(
                blank=True, help_text="API key for OpenAI integration.", null=True
            ),
        ),
    ]
