[phases.setup]
nixPkgs = [
  "python312.withPackages (ps: with ps; [ django celery gunicorn setuptools pip ])",
  "gcc"
]
cmds = ["pip install -r requirements.txt"]
[start]
cmd = "celery -A instantrealestate_backend worker --loglevel=info"
