# Generated by Django 5.2 on 2025-05-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscriptionplan_alter_subscription_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
