# Generated by Django 5.2 on 2025-05-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_alter_subscription_current_period_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionhistory",
            name="hosted_invoice_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionhistory",
            name="invoice_pdf",
            field=models.URLField(blank=True, null=True),
        ),
    ]
