# Generated by Django 5.2 on 2025-07-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_subscriptionplan_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionplan",
            old_name="stripe_product_id",
            new_name="stripe_price_id",
        ),
    ]
