# Generated by Django 5.2 on 2025-07-03 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_rename_created_at_subscription_started_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="latest_invoice_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="latest_invoice_pdf",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="latest_invoice_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SubscriptionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_invoice_id", models.CharField(max_length=255)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=8)),
                ("currency", models.CharField(max_length=10)),
                ("paid_at", models.DateTimeField()),
                ("invoice_pdf", models.URLField(blank=True, null=True)),
                ("hosted_invoice_url", models.URLField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
