# Generated by Django 5.2 on 2025-07-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_subscription_latest_invoice_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("stripe_customer_id", models.CharField(max_length=255)),
                (
                    "stripe_subscription_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("stripe_payment_intent_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
