# Generated by Django 5.2 on 2025-07-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0010_pendingsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingsubscription",
            name="status",
            field=models.CharField(default="incomplete", max_length=50),
        ),
    ]
