# Generated by Django 5.2 on 2025-07-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_pendingsubscription_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingsubscription",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
