# Generated by Django 5.2 on 2025-07-05 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0012_alter_pendingsubscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="scheduled_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_subscriptions",
                to="subscriptions.subscriptionplan",
            ),
        ),
    ]
