# Generated by Django 5.2 on 2025-07-06 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0013_subscription_scheduled_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingsubscription",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="currency",
            field=models.CharField(default="usd", max_length=10),
        ),
        migrations.DeleteModel(
            name="SubscriptionPlanChangeLog",
        ),
    ]
