# Generated by Django 5.2 on 2025-06-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instabot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instabot",
            name="email_recipients",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
