# Generated by Django 5.2 on 2025-06-17 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shared", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("home_type", models.CharField(max_length=100)),
                ("beds", models.PositiveIntegerField()),
                ("baths", models.PositiveIntegerField()),
                ("sqft", models.PositiveIntegerField()),
                ("lot_size", models.FloatField()),
                ("description", models.TextField()),
                ("ai_generated_description", models.TextField(blank=True)),
                (
                    "button1_text",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("button1_url", models.URLField(blank=True)),
                (
                    "button2_text",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("button2_url", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("email_recipients", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "keyword",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property",
                        to="shared.keyword",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
