# Generated by Django 5.2 on 2025-06-19 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_loftyproperty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="loftyproperty",
            name="image_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="loftyproperty",
            unique_together={("listing_id", "user")},
        ),
    ]
