# Generated by Django 5.2 on 2025-06-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_alter_loftyproperty_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(default="active", max_length=50),
        ),
    ]
