# Generated by Django 5.2 on 2025-06-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_property_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="image_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
